version: '3'

services:
  app:
    image: wenjing95/chatgpt-web-backend:latest
    # image: chatgpt-web-backend:latest
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: ''
      # 可选，默认值为 gpt-3.5-turbo
      API_MODEL: gpt-3.5-turbo
      # Socks代理，可选，格式为 http://127.0.0.1:10808
      SOCKS_PROXY: ''
      # HOST，可选，默认值为 0.0.0.0
      HOST: 0.0.0.0
      # PORT，可选，默认值为 3002
      PORT: 3002
  nginx:
    build: nginx
    image: wenjing95/chatgpt-web-frontend:latest
    # image: chatgpt-web-frontend:latest
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html/:/etc/nginx/html/
    links:
      - app
